language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5

addons:
  apt:
    packages:
      - parallel

sudo: false

script:
  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
